# 基础镜像使用 Java 21
FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

# 复制编译好的 JAR 包
COPY novel-gateway/target/*.jar app.jar

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# 暴露端口
EXPOSE 8080

# 启动命令
ENTRYPOINT ["java", "-Xms512m", "-Xmx512m", "-jar", "app.jar"]